---
name: MultiPlayerHardcore
main: com.jeansburger.hardcore.MultiPlayerHardcore
version: 0.0.2
api-version: 1.16
depend: ['Multiverse-Core', 'Multiverse-NetherPortals']
softdepend: ['Multiverse-Inventories']
commands:
